import { NextResponse } from 'next/server';
import { claimBillingEvent, grantSubscription, releaseBillingEvent, revokeSubscription } from '@/lib/db/repositories/billing';
import { planForProduct, verifyBillingBinding } from '@/lib/billing/creem';
import { billingActionFor } from '@/lib/billing/events';
import { creemEventDetails, verifyCreemSignature } from '@/lib/billing/webhook';

export const runtime = 'nodejs';

interface CreemEvent {
  id?: string;
  eventType?: string;
  object?: Record<string, unknown>;
}

export async function POST(req: Request) {
  const rawBody = await req.text();
  const signature = req.headers.get('creem-signature');
  const secret = process.env.CREEM_WEBHOOK_SECRET;
  if (!secret) {
    console.error('[billing] webhook_secret_missing');
    return NextResponse.json({ error: 'not_configured' }, { status: 503 });
  }
  if (!signature || !verifyCreemSignature(rawBody, signature, secret)) {
    return NextResponse.json({ error: 'invalid_signature' }, { status: 401 });
  }

  let event: CreemEvent;
  try {
    event = JSON.parse(rawBody) as CreemEvent;
  } catch {
    return NextResponse.json({ error: 'invalid_json' }, { status: 400 });
  }
  if (!event.id || !event.eventType || !event.object) {
    return NextResponse.json({ error: 'invalid_event' }, { status: 400 });
  }
  if (!(await claimBillingEvent(event.id, event.eventType))) {
    return NextResponse.json({ ok: true, duplicate: true });
  }

  try {
    const details = creemEventDetails(event.object, event.eventType);
    const bindingSecret = process.env.BETTER_AUTH_SECRET;
    const trustedDetails = {
      ...details,
      // metadata comes back through a user-editable checkout URL. Never use its userId
      // unless it carries the HMAC generated by our authenticated checkout endpoint.
      userId: bindingSecret && verifyBillingBinding(details.userId, details.binding, bindingSecret)
        ? details.userId
        : null,
    };
    const action = billingActionFor(event.eventType);
    if (action === 'grant') {
      const plan = trustedDetails.productId ? planForProduct(trustedDetails.productId) : null;
      if (!plan) return await unresolvedGrant(event.id, event.eventType, 'unknown_product', trustedDetails);
      const granted = await grantSubscription({ ...trustedDetails, plan, status: event.eventType });
      if (!granted.ok) return await unresolvedGrant(event.id, event.eventType, 'profile_not_found', trustedDetails);
    } else if (action === 'revoke') {
      const revoked = await revokeSubscription({ ...trustedDetails, status: event.eventType });
      if (!revoked) {
        console.warn('[billing] webhook_ignored', {
          eventId: event.id,
          eventType: event.eventType,
          reason: 'profile_not_found',
        });
        return NextResponse.json({ ok: true, ignored: 'profile_not_found' });
      }
    }
    console.info('[billing] webhook_processed', { eventId: event.id, eventType: event.eventType });
    return NextResponse.json({ ok: true });
  } catch (error) {
    await releaseBillingEvent(event.id).catch(() => undefined);
    console.error('[billing] webhook_failed', { eventId: event.id, eventType: event.eventType, error });
    return NextResponse.json({ error: 'processing_failed' }, { status: 500 });
  }
}

/**
 * 收到了钱但没能把套餐发出去。
 *
 * 之前这里直接返回 200 并保留去重记录，后果是最坏的一种组合：Creem 认为投递成功
 * 不再重试，而重试就算来了也会被去重挡掉 —— 这一笔永远补不回来，而且没有任何告警。
 *
 * 现在改成：释放去重记录并返回 500。Creem 会按自己的退避策略重试，
 * 期间只要用户补上账号或客户资料补全，下一次重试就能落地。
 * grantSubscription 是幂等的（套餐和积分是覆盖写），重复投递不会重复发放。
 *
 * 日志用 error 级别：这是真金白银没交付，不该混在 warn 里被忽略。
 */
async function unresolvedGrant(
  eventId: string,
  eventType: string,
  reason: 'unknown_product' | 'profile_not_found',
  details: Record<string, unknown>,
) {
  await releaseBillingEvent(eventId).catch(() => undefined);
  console.error('[billing] grant_unresolved', {
    eventId,
    eventType,
    reason,
    userId: details.userId,
    email: details.email,
    productId: details.productId,
    customerId: details.customerId,
  });
  return NextResponse.json({ error: reason }, { status: 500 });
}
